version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=support_inbox
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/support_inbox
    depends_on:
      - db
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  postgres_data: